### ISSUE TITLE
.when with array behavior different than jQuery

### ISSUE THREAD

**Issue by mdiiorio** [wookiehangover/underscore.deferred#20]
I'm seeing some differences between how jQuery and Underscore deferreds behave with regard to arrays passed in to .when(). Here's an example:

```
_.when([1, 2]).done(function() { console.log(arguments); })
[1, 2]

$.when([1, 2]).done(function() { console.log(arguments); })
[Array[2]]
```

I'd argue that jQuery's implementation is better because I'm getting back what I'm passing in. But it's not a big deal to adapt to Underscore deferred's behavior.

So I'm not sure if this is an oversight or intended behavior. If it's intended behavior it'd be nice to indicate in the documentation because it tripped me up for a bit.

**Comment by ghost** [comment]
It's intentional, but documented in the [`_.when` section](https://github.com/wookiehangover/underscore.deferred#_when) under "Enhancements / Changes."

**Comment by wookiehangover** [comment]
Thanks for responding, @kitcambridge 

This is indeed intentional.
