### ISSUE TITLE
Possible Name Change?

### ISSUE THREAD

**Issue by wookiehangover** [wookiehangover/underscore.deferred#7]
So the direction of this project was originally solely to integrate with Underscore.js, but pretty quickly we moved away from having that as a hard dependency. Love to get some feedback on this @tbranyen @rwaldron

**Comment by rwaldron** [comment]
What were you thinking about calling it? The current name is totally accurate, right?

**Comment by wookiehangover** [comment]
Maybe shortening it to "undeferred" or something along those lines.

The name is accurate in the sense that it works as an underscore mixin, but I think it potentially has the implication that underscore is a hard dependency.

**Comment by rwaldron** [comment]
I love it.
